### ISSUE TITLE
Formatting and linting

### ISSUE THREAD

**Issue by fissoreg** [baioc/crowd-sourced#10]
It would be nice to take care of formatting and linting of the code (Python side).

I suggest:
- [black](https://github.com/psf/black) formatting
- [flake8](https://github.com/PyCQA/flake8) linting

**Comment by Rubix982** [comment]
We can add an automated script to deal with this. I think we can add top root level requirements.txt where we can install these dependencies, and then we can run the lines as we see fit.

**Comment by Rubix982** [comment]
The aforementioned PR solves this issue. Closing.
