### ISSUE TITLE
Add a couple of different types of labeling problems

### ISSUE THREAD

**Issue by baioc** [baioc/crowd-sourced#2]
Training widget ideas and initial UI sketches (I'm no designer btw, feel free to make changes):

- Classification (text or image), drop-down list or radio buttons
![Options](https://user-images.githubusercontent.com/27034173/121346529-85766080-c926-11eb-94b0-75b0a4197401.png)

- Classification (image), text box
![Label](https://user-images.githubusercontent.com/27034173/121346568-91622280-c926-11eb-8792-e50e7b31d847.png)

- Detection/Segmentation (image), selection grid
![Select](https://user-images.githubusercontent.com/27034173/121346583-958e4000-c926-11eb-9087-7972c0d146a5.png)

- Multi-Classification (text or image), check-boxes
  Probably the same layout as the single-classification, but with check-boxes

Each one of these would probably need a different:
1. UI template in the frontend;
2. document schema in the backend.
Tasks can be partitioned accordingly.

**Comment by Rubix982** [comment]
Acknowledged. I'm taking the work for this frontend design.

**Comment by Rubix982** [comment]
Frontend completed with PR #14
