### ISSUE TITLE
Getting Data Prepared For The Database

### ISSUE THREAD

**Issue by Rubix982** [baioc/crowd-sourced#6]
As discussed previously in the team meeting, we need to have the textual and graphical data ready for database retrieval and forwarding.

**Comment by fissoreg** [comment]
3 datasets for now:

- [unsplash nature](https://unsplash.com/t/nature): we can label the category of the main subject of the picture, e.g. mountains, sky, animal, flowers...
- [KITTI semantic](http://www.cvlibs.net/datasets/kitti/eval_instance_seg.php?benchmark=instanceSeg2015) (autonomous driving): select cars/bikes/pedestrians... in a CAPTCHA-style fashion
- [sentiment analysis](https://www.kaggle.com/kazanova/sentiment140) (from Twitter): label positive/negative/neutral

For MongoDB, we're gonna have 2 collections:

Datasets (this is the schema for each dataset):
- name (id)
- content_type (image/text)
- label_type (categorical for now)
- options (list of options)

Data (this is the actual data pointers + collected labels):
- id
- url
- labels

I will take care of writing some scripts to download the datasets and populate the MongoDB instance. This will be included in the Makefile. In the meanwhile, you should be able to work with some placeholders following the above schemas.

**Comment by Rubix982** [comment]
Acknowledged, @fissoreg . Thank you.

**Comment by fissoreg** [comment]
Update on the schemas (from `mongoengine`):

```
class Dataset(Document):
    name = StringField(primary_key=True)
    content_type = StringField(required=True, choices=["IMAGE", "TEXT"])
    message = StringField(required=True)
    label_type = StringField(required=True, choices=["CLASS", "LABEL", "GRID"])
    options = ListField(StringField())


class Image(Document):
    dataset = ReferenceField(Dataset, required=True)
    url = StringField(required=True, unique_with="dataset")
    labels = DictField(StringField)

class Tweet(Document):
    _id = IntField(primary_key=True)
    dataset = ReferenceField(Dataset, required=True)
    tweet = StringField(required=True) #, unique_with="dataset")
    labels = DictField(StringField)
```

**Comment by Rubix982** [comment]
Added the new changes to backend as the DB schema representation.
